import type { ScoutResponse } from './types'

function download(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function slug(company: string): string {
  return company.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
}

export function exportJson(result: ScoutResponse): void {
  download(
    `scout-${slug(result.company)}.json`,
    JSON.stringify(result, null, 2),
    'application/json',
  )
}

export function exportMarkdown(result: ScoutResponse): void {
  const { company, researchFocus, budget, brief, spendLedger, totalSpent } = result
  const date = new Date().toISOString().slice(0, 10)

  const lines: string[] = [
    `# Competitive Intelligence Report: ${company}`,
    '',
    `**Research Focus:** ${researchFocus}  `,
    `**Budget:** $${budget.toFixed(2)} USDC | **Spent:** $${totalSpent.toFixed(4)} USDC | **Date:** ${date}`,
    '',
    '---',
    '',
    '## Overview',
    '',
    brief.overview,
    '',
    '## Top Competitors',
    '',
    ...brief.competitors.flatMap(c => [`### ${c.name}`, '', c.summary, '']),
    '## Recent Moves',
    '',
    ...brief.recentMoves.map(m => `- **${m.date}** — ${m.event} ([source](${m.source}))`),
    '',
    '## Customer Sentiment',
    '',
    `**Score:** ${brief.sentiment.score} / 100`,
    '',
    brief.sentiment.summary,
    '',
    '## Pricing Intel',
    '',
    brief.pricing.summary,
    '',
    ...brief.pricing.tiers.map(t => `- ${t}`),
    '',
    '## Tech Signals',
    '',
    brief.techSignals.summary,
    '',
    `**Signals:** ${brief.techSignals.signals.join(', ')}`,
    '',
    '---',
    '',
    '## Spend Ledger',
    '',
    '| Category | Query | Cost | Receipt |',
    '|---|---|---|---|',
    ...spendLedger.map(e =>
      `| ${e.category} | ${e.query} | $${e.cost.toFixed(3)} USDC | [${e.receipt.slice(0, 10)}…](https://basescan.org/tx/${e.receipt}) |`
    ),
    '',
    `**Total:** $${totalSpent.toFixed(4)} USDC spent of $${budget.toFixed(2)} USDC budget`,
    '',
    `_Generated by Scout — autonomous competitive intelligence_`,
  ]

  download(
    `scout-${slug(company)}.md`,
    lines.join('\n'),
    'text/markdown',
  )
}

export function exportPdf(result: ScoutResponse): void {
  const { company, researchFocus, budget, brief, spendLedger, totalSpent } = result
  const date = new Date().toISOString().slice(0, 10)

  const competitorRows = brief.competitors
    .map(c => `<div class="card"><strong>${c.name}</strong><p>${c.summary}</p></div>`)
    .join('')

  const moveRows = brief.recentMoves
    .map(m => `<li><span class="date">${m.date}</span> ${m.event} <a href="${m.source}">[source]</a></li>`)
    .join('')

  const tierRows = brief.pricing.tiers
    .map(t => `<li>${t}</li>`)
    .join('')

  const signalTags = brief.techSignals.signals
    .map(s => `<span class="tag">${s}</span>`)
    .join('')

  const ledgerRows = spendLedger
    .map(e => `<tr><td>${e.category}</td><td>${e.query}</td><td>$${e.cost.toFixed(3)}</td><td><a href="https://basescan.org/tx/${e.receipt}">${e.receipt.slice(0, 14)}…</a></td></tr>`)
    .join('')

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Scout — ${company}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 13px; color: #111; padding: 40px; max-width: 860px; margin: 0 auto; }
  h1 { font-size: 22px; font-weight: 700; margin-bottom: 4px; }
  .meta { color: #555; font-size: 12px; margin-bottom: 24px; }
  h2 { font-size: 14px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em; color: #444; border-bottom: 1px solid #e5e5e5; padding-bottom: 6px; margin: 24px 0 12px; }
  p { line-height: 1.6; color: #222; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
  .card { border: 1px solid #e5e5e5; border-radius: 6px; padding: 12px; }
  .card strong { display: block; margin-bottom: 4px; }
  ul { padding-left: 18px; line-height: 2; }
  .date { font-family: monospace; font-size: 11px; color: #888; margin-right: 6px; }
  .tags { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 10px; }
  .tag { border: 1px solid #ddd; border-radius: 4px; padding: 2px 8px; font-size: 11px; color: #444; }
  .score-bar { height: 6px; background: #eee; border-radius: 3px; margin: 8px 0; }
  .score-fill { height: 100%; border-radius: 3px; background: ${brief.sentiment.score >= 70 ? '#22c55e' : brief.sentiment.score >= 40 ? '#eab308' : '#ef4444'}; width: ${brief.sentiment.score}%; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; }
  th { background: #f5f5f5; text-align: left; padding: 6px 8px; border: 1px solid #e5e5e5; }
  td { padding: 5px 8px; border: 1px solid #e5e5e5; color: #333; }
  a { color: #2563eb; text-decoration: none; }
  .footer { margin-top: 32px; font-size: 11px; color: #aaa; text-align: center; border-top: 1px solid #eee; padding-top: 12px; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
<h1>Competitive Intelligence: ${company}</h1>
<p class="meta">Focus: ${researchFocus} &nbsp;·&nbsp; Budget: $${budget.toFixed(2)} USDC &nbsp;·&nbsp; Spent: $${totalSpent.toFixed(4)} USDC &nbsp;·&nbsp; ${date}</p>

<h2>Overview</h2>
<p>${brief.overview}</p>

<h2>Top Competitors</h2>
<div class="grid">${competitorRows}</div>

<h2>Recent Moves</h2>
<ul>${moveRows}</ul>

<h2>Customer Sentiment — ${brief.sentiment.score}/100</h2>
<div class="score-bar"><div class="score-fill"></div></div>
<p>${brief.sentiment.summary}</p>

<h2>Pricing Intel</h2>
<p>${brief.pricing.summary}</p>
<ul>${tierRows}</ul>

<h2>Tech Signals</h2>
<p>${brief.techSignals.summary}</p>
<div class="tags">${signalTags}</div>

<h2>Spend Ledger</h2>
<table>
<tr><th>Category</th><th>Query</th><th>Cost</th><th>Receipt</th></tr>
${ledgerRows}
</table>

<p class="footer">Generated by Scout · autonomous competitive intelligence · powered by Circle, Tavily, Nebius</p>
</body>
</html>`

  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.focus()
  win.print()
}
